history for ensembles and final layer option.
sandialabs/quinn pull request #2
Opened 2023-05-03 11:19 UTC by odiazib

1)	Adding history attribute in learner class; however, I only include training history of last iteration.  
2)	Adding “sum” option in final_layer in ResNets. This operation will reduce one dimension in the output tensor. 
3)	Adding relative error computation for ensembles.

2023-05-09 15:47 UTC, ksargsyan requested changes

2023-05-09 15:47 UTC, ksargsyan commented on quinn/ens/learner.py
> +        history (list of doubles): List containing training history of last iteration, namely, [fepoch, loss_trn, loss_trn_full, loss_val]
Please reword to list[double]

2023-05-09 15:47 UTC, ksargsyan commented on quinn/ens/learner.py
> +        history (list of doubles): List containing training history of last iteration, namely, [fepoch, loss_trn, loss_trn_full, loss_val]
Also, I don't understand why this attribute is needed and why should it be called history if it is only the last iteration and not the full history.

2023-05-09 15:47 UTC, ksargsyan commented on quinn/nns/nnbase.py
> +            dict: Dictionary of the results. Keys 'best_fepoch', 'best_epoch', 'best_loss', 'best_nnmodel', 'history'.
Remind me why we need to return dict and not the best model. I am afraid several codes relying on these won't be backward compatible.

2023-05-09 15:47 UTC, ksargsyan commented on quinn/utils/metrics.py
> +def rel_l2_ens(predictions, targets):
This needs to be commented a lot better. It seems it assumes certain structure/dimension of the arrays. There must be a more pythonic way of doing this.

2023-05-10 15:25 UTC, odiazib commented on quinn/nns/nnbase.py
> +            dict: Dictionary of the results. Keys 'best_fepoch', 'best_epoch', 'best_loss', 'best_nnmodel', 'history'.
I reverted this change.

2023-05-10 15:26 UTC, odiazib commented on quinn/ens/learner.py
> +        history (list of doubles): List containing training history of last iteration, namely, [fepoch, loss_trn, loss_trn_full, loss_val]
I decided to remove this attribute. We can access to the training history using: `learner.nnmodel.history[-1]`

2023-05-10 16:01 UTC, odiazib commented on quinn/utils/metrics.py
> +def rel_l2_ens(predictions, targets):
Done.

2023-05-15 19:56 UTC, merged